# codegen.toml

[[models]]
path = "../interface"
files = [
    "chatlog.smithy",
    "outbound.smithy" 
]

[[models]]
# Location of dependencies may be either a path to a directory, or a url prefix
# If a relative path is used, it is relative to the location of this codegen.toml
#path = "/path/to/my-interfaces"
url = "https://wasmcloud.github.io/interfaces/idl/org.wasmcloud"
files = [ "wasmcloud-core.smithy", "wasmcloud-model.smithy" ]


##
## HTML documentation output
##
[html]

# (optional) template dir to scan (overrides compiled-in templates)
#templates = "docgen/templates"
# Top-level output directory for html generated files
output_dir = "html"

# Additional parameters for html generation
[html.parameters]

# name of template for page generation (default: 'namespace_doc')
#doc_template = "namespace_doc"

# whether to use minified tailwind.css (default false)
minified = true


##
## Rust language output
##
[rust]

# top-level output directory for rust files.
output_dir = "."

[rust.parameters]

# File-specific settings contain the following settings
# [[rust.files]]
# path - (required) path for generated output file, relative to output_dir above
# hbs - handlebars template name (without .hbs extension)
# Only applicable if file is generated by a handlebars template
# create_only - whether file should be generated only with --create (default false)
# namespace - limit generated shapes to shapes in this namespace
# * - any other fields are per-file parameters passed to codegen and renderer

# Additional namespaces may be added to this library crate by adding
# a rust source file below for each namespace,
# and importing each of them into src/lib.rs

[[rust.files]]
path = "src/chatlog.rs"
namespace = "com.cosmonic.samples.mcchat.chatlog"

[[rust.files]]
path = "src/outbound.rs"
namespace = "com.cosmonic.samples.mcchat.outbound"