# This is a full example of how to run the kvcounter actor exposed with the
# managed providers for the HTTP and KeyValue capabilities.

apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: kvcounter
  annotations:
    version: v1.0.0
    description: "wasmCloud Key Value Counter Example"
spec:
  components:
    - name: kvcounter
      type: actor
      properties:
        image: ghcr.io/cosmonic/kvcounter:0.1.0
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
        - type: linkdef
          properties:
            target: keyvalue
        - type: linkdef
          properties:
            target: httpserver
            values:
              ADDRESS: 0.0.0.0:8081
    - name: httpserver
      type: capability
      properties:
        image: cosmonic.azurecr.io/httpserver_wormhole:0.6.2
        contract: wasmcloud:httpserver
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
            spread:
              - name: wormholespread
                requirements:
                  cosmonic_managed: "true"
    - name: keyvalue
      type: capability
      properties:
        image: cosmonic.azurecr.io/builtin_keyvalue:0.2.5
        contract: wasmcloud:keyvalue
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
            spread:
              - name: kvspread
                requirements:
                  cosmonic_managed: "true"
