# This is a full example of a multi-channel chat application. It uses the following components:
# - chatlog: A wasmCloud actor that stores the chat log in a key-value store
# - httpchannel: A wasmCloud actor that uses the HTTP Server provider to listen for HTTP requests
# - natschannel: A wasmCloud actor that uses the NATS Messaging provider to listen for NATS messages
# - apigateway: A wasmCloud actor thas is invoked through actor-to-actor calls to coordinate messages between the channels

apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: multi-channel-chat
  annotations:
    version: v1.0.0
    description: "Multi-Channel Chat"
spec:
  components:
    - name: apigateway
      type: actor
      properties:
        image: cosmonic.azurecr.io/mcc_apigateway:0.1.0
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
    
    - name: chatlog
      type: actor
      properties:
        image: cosmonic.azurecr.io/mcc_chatlog:0.1.0
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
        - type: linkdef
          properties:
            target: keyvalue

    - name: httpchannel
      type: actor
      properties:
        image: cosmonic.azurecr.io/mcc_httpchannel:0.1.0
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
        - type: linkdef
          properties:
            target: httpserver
    
    - name: natschannel
      type: actor
      properties:
        image: cosmonic.azurecr.io/mcc_natschannel:0.1.0
      traits:
        - type: spreadscaler
          properties:
            replicas: 3
        - type: linkdef
          properties:
            target: messaging

    - name: httpserver
      type: capability
      properties:
        contract: wasmcloud:httpserver
        image: cosmonic.azurecr.io/httpserver_wormhole:0.5.4
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
            spread:
              - name: wormholespread
                requirements:
                  cosmonic_managed: 'true'

    - name: keyvalue
      type: capability
      properties:
        contract: wasmcloud:keyvalue
        image: cosmonic.azurecr.io/builtin_keyvalue:0.2.4
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
            spread:
              - name: kvspread
                requirements:
                  cosmonic_managed: 'true'

    - name: messaging
      type: capability
      properties:
        contract: wasmcloud:messaging
        image: wasmcloud.azurecr.io/nats_messaging:0.17.2
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
