# This is a full example of how to run the hello actor exposed with an HTTP server on Cosmonic.
# This example leverages WADM running: https://github.com/wasmCloud/wadm/tree/main/wadm.
#
# This example starts a webserver on Cosmonic and runs the hello world on a remote host.
# See other examples for different scenarios.

apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: hello
  annotations:
    version: v1.0.0-stargate
    description: "Cosmonic Hello World Example"
spec:
  components:
    - name: hello
      type: actor
      properties:
        image: ghcr.io/cosmonic/hello:0.1.0
      traits:
        - properties:
            replicas: 1
            spread:
              - name: stargate
                requirements:
                  # hostcore.os: macos
                  stargate: "true"
          type: spreadscaler
        - properties:
            target: httpserver
          type: linkdef
    - name: httpserver
      properties:
        contract: wasmcloud:httpserver
        image: cosmonic.azurecr.io/httpserver_wormhole:0.6.2
      traits:
        - properties:
            replicas: 1
            spread:
              - name: oncosmonic
                requirements:
                  cosmonic_managed: "true"
          type: spreadscaler
      type: capability
