# This is a full example of how to run the hello actor exposed with an HTTP server on Cosmonic. 
# This example leverages WADM running: https://github.com/wasmCloud/wadm/tree/main/wadm.
#
# All components are started on Cosmonic.  See other examples for different scenarios.

apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: hello
  annotations:
    version: v1.0.0-cosmonic
    description: "Cosmonic Hello World Example"
spec:
  components:
    - name: hello
      type: actor
      properties:
        image: cosmonic.azurecr.io/hello:0.1.0
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
        - type: linkdef
          properties:
            target: httpserver
    - name: httpserver
      properties:
        contract: wasmcloud:httpserver
        image: cosmonic.azurecr.io/httpserver_wormhole:0.5.4
      traits:
        - properties:
            replicas: 1
            spread:
              - name: oncosmonic
                requirements:
                  cosmonic_managed: 'true'
          type: spreadscaler
      type: capability