// This file is @generated by wasmcloud/weld-codegen 0.5.0.
// It is not intended for manual editing.
// namespace: com.cosmonic.samples.mcchat.outbound

#[allow(unused_imports)]
use async_trait::async_trait;
#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use std::{borrow::Borrow, borrow::Cow, io::Write, string::ToString};
#[allow(unused_imports)]
use wasmbus_rpc::{
    cbor::*,
    common::{
        deserialize, message_format, serialize, Context, Message, MessageDispatch, MessageFormat,
        SendOpts, Transport,
    },
    error::{RpcError, RpcResult},
    Timestamp,
};

#[allow(dead_code)]
pub const SMITHY_VERSION: &str = "1.0";

#[derive(Clone, Debug, Default, Deserialize, Eq, PartialEq, Serialize)]
pub struct OutboundMessage {
    #[serde(default)]
    pub body: String,
    #[serde(rename = "sourceChannel")]
    #[serde(default)]
    pub source_channel: String,
    #[serde(rename = "sourceUser")]
    #[serde(default)]
    pub source_user: String,
}

// Encode OutboundMessage as CBOR and append to output stream
#[doc(hidden)]
#[allow(unused_mut)]
pub fn encode_outbound_message<W: wasmbus_rpc::cbor::Write>(
    mut e: &mut wasmbus_rpc::cbor::Encoder<W>,
    val: &OutboundMessage,
) -> RpcResult<()>
where
    <W as wasmbus_rpc::cbor::Write>::Error: std::fmt::Display,
{
    e.map(3)?;
    e.str("body")?;
    e.str(&val.body)?;
    e.str("sourceChannel")?;
    e.str(&val.source_channel)?;
    e.str("sourceUser")?;
    e.str(&val.source_user)?;
    Ok(())
}

// Decode OutboundMessage from cbor input stream
#[doc(hidden)]
pub fn decode_outbound_message(
    d: &mut wasmbus_rpc::cbor::Decoder<'_>,
) -> Result<OutboundMessage, RpcError> {
    let __result = {
        let mut body: Option<String> = None;
        let mut source_channel: Option<String> = None;
        let mut source_user: Option<String> = None;

        let is_array = match d.datatype()? {
            wasmbus_rpc::cbor::Type::Array => true,
            wasmbus_rpc::cbor::Type::Map => false,
            _ => {
                return Err(RpcError::Deser(
                    "decoding struct OutboundMessage, expected array or map".to_string(),
                ))
            }
        };
        if is_array {
            let len = d.fixed_array()?;
            for __i in 0..(len as usize) {
                match __i {
                    0 => body = Some(d.str()?.to_string()),
                    1 => source_channel = Some(d.str()?.to_string()),
                    2 => source_user = Some(d.str()?.to_string()),
                    _ => d.skip()?,
                }
            }
        } else {
            let len = d.fixed_map()?;
            for __i in 0..(len as usize) {
                match d.str()? {
                    "body" => body = Some(d.str()?.to_string()),
                    "sourceChannel" => source_channel = Some(d.str()?.to_string()),
                    "sourceUser" => source_user = Some(d.str()?.to_string()),
                    _ => d.skip()?,
                }
            }
        }
        OutboundMessage {
            body: if let Some(__x) = body {
                __x
            } else {
                return Err(RpcError::Deser(
                    "missing field OutboundMessage.body (#0)".to_string(),
                ));
            },

            source_channel: if let Some(__x) = source_channel {
                __x
            } else {
                return Err(RpcError::Deser(
                    "missing field OutboundMessage.source_channel (#1)".to_string(),
                ));
            },

            source_user: if let Some(__x) = source_user {
                __x
            } else {
                return Err(RpcError::Deser(
                    "missing field OutboundMessage.source_user (#2)".to_string(),
                ));
            },
        }
    };
    Ok(__result)
}
/// wasmbus.actorReceive
#[async_trait]
pub trait Outbound {
    async fn publish_message(&self, ctx: &Context, arg: &OutboundMessage) -> RpcResult<bool>;
}

/// OutboundReceiver receives messages defined in the Outbound service trait
#[doc(hidden)]
#[async_trait]
pub trait OutboundReceiver: MessageDispatch + Outbound {
    async fn dispatch(&self, ctx: &Context, message: Message<'_>) -> Result<Vec<u8>, RpcError> {
        match message.method {
            "PublishMessage" => {
                let value: OutboundMessage = wasmbus_rpc::common::deserialize(&message.arg)
                    .map_err(|e| RpcError::Deser(format!("'OutboundMessage': {}", e)))?;

                let resp = Outbound::publish_message(self, ctx, &value).await?;
                let buf = wasmbus_rpc::common::serialize(&resp)?;

                Ok(buf)
            }
            _ => Err(RpcError::MethodNotHandled(format!(
                "Outbound::{}",
                message.method
            ))),
        }
    }
}

/// OutboundSender sends messages to a Outbound service
/// client for sending Outbound messages
#[derive(Debug)]
pub struct OutboundSender<T: Transport> {
    transport: T,
}

impl<T: Transport> OutboundSender<T> {
    /// Constructs a OutboundSender with the specified transport
    pub fn via(transport: T) -> Self {
        Self { transport }
    }

    pub fn set_timeout(&self, interval: std::time::Duration) {
        self.transport.set_timeout(interval);
    }
}

#[cfg(not(target_arch = "wasm32"))]
impl<'send> OutboundSender<wasmbus_rpc::provider::ProviderTransport<'send>> {
    /// Constructs a Sender using an actor's LinkDefinition,
    /// Uses the provider's HostBridge for rpc
    pub fn for_actor(ld: &'send wasmbus_rpc::core::LinkDefinition) -> Self {
        Self {
            transport: wasmbus_rpc::provider::ProviderTransport::new(ld, None),
        }
    }
}
#[cfg(target_arch = "wasm32")]
impl OutboundSender<wasmbus_rpc::actor::prelude::WasmHost> {
    /// Constructs a client for actor-to-actor messaging
    /// using the recipient actor's public key
    pub fn to_actor(actor_id: &str) -> Self {
        let transport =
            wasmbus_rpc::actor::prelude::WasmHost::to_actor(actor_id.to_string()).unwrap();
        Self { transport }
    }
}
#[async_trait]
impl<T: Transport + std::marker::Sync + std::marker::Send> Outbound for OutboundSender<T> {
    #[allow(unused)]
    async fn publish_message(&self, ctx: &Context, arg: &OutboundMessage) -> RpcResult<bool> {
        let buf = wasmbus_rpc::common::serialize(arg)?;

        let resp = self
            .transport
            .send(
                ctx,
                Message {
                    method: "Outbound.PublishMessage",
                    arg: Cow::Borrowed(&buf),
                },
                None,
            )
            .await?;

        let value: bool = wasmbus_rpc::common::deserialize(&resp)
            .map_err(|e| RpcError::Deser(format!("'{}': Boolean", e)))?;
        Ok(value)
    }
}
