apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    description: A Concordance bank account example
    version: v0.1.0
  name: bank-account
spec:
  components:
    - name: catalog
      properties:
        image: ghcr.io/cosmonic/bankaccount_catalog:0.1.0
      traits:
        - properties:
            replicas: 3
            spread:
              - name: oncosmonic
                requirements:
                  cosmonic_managed: "true"
          type: spreadscaler
        - properties:
            target: httpserver
          type: linkdef
      type: actor
    - name: projector
      properties:
        image: ghcr.io/cosmonic/bankaccount_projector:0.1.0
      traits:
        - properties:
            replicas: 1
            spread:
              - name: oncosmonic
                requirements:
                  cosmonic_managed: "true"
          type: spreadscaler
        - properties:
            target: concordance
            values:
              INTEREST: >-
                account_created,funds_deposited,funds_released,funds_reserved,funds_withdrawn,wire_transfer_initiated
              NAME: bankaccount_projector
              ROLE: projector
          type: linkdef
        - properties:
            target: keyvalue
          type: linkdef
      type: actor
    - name: aggregate
      properties:
        image: ghcr.io/cosmonic/bankaccount_aggregate:0.1.0
      traits:
        - properties:
            replicas: 1
            spread:
              - name: oncosmonic
                requirements:
                  cosmonic_managed: "true"
          type: spreadscaler
        - properties:
            target: concordance
            values:
              INTEREST: bankaccount
              KEY: accountNumber
              NAME: bankaccount
              ROLE: aggregate
          type: linkdef
      type: actor
    - name: processmanager
      properties:
        image: ghcr.io/cosmonic/wiretransfer_processmanager:0.1.0
      traits:
        - properties:
            replicas: 1
            spread:
              - name: oncosmonic
                requirements:
                  cosmonic_managed: "true"
          type: spreadscaler
        - properties:
            target: concordance
            values:
              INTEREST: >-
                {"start":"wire_transfer_initiated","advance":["funds_reserved","wire_transfer_succeeded","wire_transfer_failed"],"stop":["funds_committed","funds_released"]}
              KEY: wireTransferId
              NAME: interbankxfer
              ROLE: process_manager
          type: linkdef
      type: actor
    - name: concordance
      properties:
        config:
          js_domain: cosmonic
          nats_url: nats://0.0.0.0:4222
        contract: cosmonic:eventsourcing
        image: registry.hub.docker.com/cosmonic/concordance:0.1.0
        link_name: default
      traits:
        - properties:
            replicas: 1
            spread:
              - name: oncosmonic
                requirements:
                  cosmonic_managed: "true"
          type: spreadscaler
      type: capability
    - name: keyvalue
      properties:
        contract: wasmcloud:keyvalue
        image: cosmonic.azurecr.io/builtin_keyvalue:0.2.5
      traits:
        - properties:
            replicas: 1
            spread:
              - name: oncosmonic
                requirements:
                  cosmonic_managed: "true"
          type: spreadscaler
      type: capability
    - name: httpserver
      properties:
        contract: wasmcloud:httpserver
        image: cosmonic.azurecr.io/httpserver_wormhole:0.6.2
      traits:
        - properties:
            replicas: 1
            spread:
              - name: oncosmonic
                requirements:
                  cosmonic_managed: "true"
          type: spreadscaler
      type: capability
