# This is a full example of how to run the blobby example.
# This requires you to have WADM running: https://github.com/wasmCloud/wadm/
# You can deploy this example with a simple command:
#
# `wash app deploy wadm.yaml`

apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: blobby
  annotations:
    version: v0.0.1
    description: "wasmCloud HTTP Server"
spec:
  components:
    - name: blobby
      type: actor
      properties:
        image: wasmcloud.azurecr.io/blobby:0.2.0
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
        - type: linkdef
          properties:
            target: httpserver
        - type: linkdef
          properties:
            target: blobstore
            values:
              ROOT: "/tmp"

    # Capability Providers
    - name: httpserver
      type: capability
      properties:
        image: cosmonic.azurecr.io/httpserver_wormhole:0.6.2
        contract: wasmcloud:httpserver
    - name: blobstore
      type: capability
      properties:
        image: wasmcloud.azurecr.io/blobstore_fs:0.3.1
        contract: wasmcloud:blobstore
