name: Build and test Multi Channel Chat
on:
  pull_request:
    branches: [main]
    paths:
      - "multi-channel-chat/**"

env:
  working-directory: "./multi-channel-chat"
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        working-directory:
          - multi-channel-chat/api-gateway
          - multi-channel-chat/chatlog
          - multi-channel-chat/http-channel
          - multi-channel-chat/nats-channel
    steps:
      - uses: actions/checkout@v3
      - name: Add wasm32-unknown-unknown
        run: rustup target add wasm32-unknown-unknown
      - name: Check formatting
        run: cargo fmt -- --check
        shell: bash
        working-directory: ${{ matrix.working-directory }}
      - name: Build actor
        run: cargo build
        working-directory: ${{ matrix.working-directory }}
      - name: Check lints with clippy
        run: |
          rustup component add clippy
          cargo clippy
        working-directory: ${{ matrix.working-directory }}