name: Build and test HTTP File Server
on:
  pull_request:
    branches: [main]
    paths:
      - "http-file-server/rust/**"

env:
  working-directory: "./http-file-server"
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wasmcloud/common-actions/install-wash@main
      - name: Add wasm32-unknown-unknown
        run: rustup target add wasm32-unknown-unknown
      - name: Build actor
        run: cargo build
        working-directory: ${{ env.working-directory }}/rust
      - name: Check formatting
        run: cargo fmt -- --check
        shell: bash
        working-directory: ${{ env.working-directory }}/rust

      - name: Check lints with clippy
        run: |
          rustup component add clippy
          cargo clippy
        working-directory: ${{ env.working-directory }}/rust
