name: Release KVCounter to AzureCR
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "kvcounter/**"
    tags:
      - "v*"
env:
  # For the release action, you'll have to set the following variables
  WASH_ISSUER_KEY: ${{ secrets.COSMONIC_ACCOUNT_OFFICIAL }}
  WASH_SUBJECT_KEY: ${{ secrets.AWESOME_COSMONIC_KVCOUNTER_KEY }}
  working-directory: "./kvcounter"
jobs:
  build_signed_actor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wasmcloud/common-actions/install-wash@main
      - name: Add wasm32-unknown-unknown
        run: rustup target add wasm32-unknown-unknown
        working-directory: ${{ env.working-directory }}/rust
      # Once you've written unit tests for your actor, you can uncomment
      # the two lines below to automatically run tests
      # - name: Test actor
      #   run: cargo test --target x86_64-unknown-linux-gnu -- --nocapture
      - name: Build and sign wasmCloud actor
        env:
          WASH_ISSUER_KEY: ${{ env.WASH_ISSUER_KEY }}
          WASH_SUBJECT_KEY: ${{ env.WASH_SUBJECT_KEY }}
        run: |
            wash new actor --path rust kvcounter
            wash build -p kvcounter
        shell: bash
        working-directory: ${{ env.working-directory }}
      - name: Upload signed actor to GH Actions
        uses: actions/upload-artifact@v3
        with:
          name: wasmcloud-actor
          path: ${{ env.working-directory }}/rust/build/*_s.wasm
      - name: Remove project
        run: rm -rf ${{ env.working-directory }}/kvcounter

  artifact_release:
    needs: build_signed_actor
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wasmcloud/common-actions/install-wash@main
      - name: Download signed actor
        uses: actions/download-artifact@v3
        with:
          name: wasmcloud-actor
          path: ${{ env.working-directory }}/rust/build
      - name: Determine actor name
        run: |
          echo "actor-name=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[].name')" >> $GITHUB_ENV
        working-directory: ${{ env.working-directory }}/rust
      - name: Determine actor version
        if: startswith(github.ref, 'refs/tags/') # Only run on tag push
        run: |
          echo "actor-version=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[].version')" >> $GITHUB_ENV
        working-directory: ${{ env.working-directory }}/rust
      - name: Determine actor version (main)
        if: ${{ !startswith(github.ref, 'refs/tags/') }}
        run: |
          echo "actor-version=latest" >> $GITHUB_ENV
        working-directory: ${{ env.working-directory }}/rust
      - name: Push actor to AzureCR
        uses: wasmcloud/common-actions/oci-artifact-release@main
        with:
          artifact-path: ${{ env.working-directory }}/rust/build/${{ env.actor-name }}_s.wasm
          oci-url: ${{ secrets.AZURECR_PUSH_URL }}   
          oci-repository: ${{ env.actor-name }}
          oci-version: ${{ env.actor-version }}
          oci-username: ${{ secrets.COSMONIC_AZURECR_PUSH_USER }}
          oci-password: ${{ secrets.COSMONIC_AZURECR_PUSH_PASSWORD }}